# Generated by Django 4.2.2 on 2024-05-18 16:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_photo_de_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_de_profile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo_de_profile'),
        ),
    ]
